name: Generate README stats

on:
  schedule:
    - cron: '25 12 * * 1'  # Runs at 12:25 PM UTC every Monday (which is 2:25 PM Monday Cairo Time)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate README
        run: |
          echo '# My GitHub Stats' > README.md
          echo '![GitHub Stats](https://github-readme-stats.vercel.app/api?username=omarahmedx14&show_icons=true&count_private=true)' >> README.md
          echo '![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=omarahmedx14&layout=compact)' >> README.md
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Commit README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with GitHub stats"
          git push --set-upstream https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main

          
